# Generated by Django 5.1.4 on 2025-04-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='theme',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
